# Generated by Django 5.2.1 on 2025-06-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_photo', models.ImageField(upload_to='photos')),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_price', models.PositiveIntegerField()),
                ('purcharse_price', models.PositiveIntegerField(default=0)),
                ('item_description', models.TextField()),
                ('exp_date', models.DateField()),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_minimum', models.PositiveIntegerField(default=10)),
                ('is_limited', models.BooleanField(default=False)),
                ('max_quantity', models.PositiveIntegerField(default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.category')),
            ],
        ),
    ]
