# Generated by Django 5.2.3 on 2025-07-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0007_possalesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
