# Generated by Django 5.2.3 on 2025-07-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0009_customerpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
