# Generated by Django 5.2.3 on 2025-07-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0010_cart_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('disease_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disease_symptom', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_phnumber', models.CharField(blank=True, null=True)),
                ('supplier_location', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.disease'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.supplier'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.supplier'),
        ),
    ]
