# Generated by Django 5.2.3 on 2025-07-04 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0012_purchaseorder_purchaseitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='supplier',
            new_name='primary_supplier',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purchase_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_phnumber',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='order_date',
        ),
        migrations.AddField(
            model_name='item',
            name='last_ordered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.item'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.item'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
