# Generated by Django 5.2.3 on 2025-07-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0013_rename_supplier_item_primary_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
