# Generated by Django 5.2.3 on 2025-07-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0014_supplier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='disease',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
