# Generated by Django 5.2.3 on 2025-07-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0015_remove_item_disease_delete_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='source',
            field=models.CharField(choices=[('pos', 'POS'), ('online', 'Online')], default='online', max_length=10),
        ),
    ]
