# Generated by Django 5.2.3 on 2025-07-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0016_cart_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
