# Generated by Django 5.2.1 on 2025-07-16 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0019_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
