# Generated by Django 5.2.1 on 2025-07-22 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0021_chatbot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='source',
            field=models.CharField(choices=[('pos', 'POS'), ('online', 'Online')], default='online', max_length=10, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='answers',
            field=models.TextField(blank=True, null=True, verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='timeline',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='customerpos',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customerpos',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customerpos',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='item',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='exp_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_limited',
            field=models.BooleanField(default=False, verbose_name='Limited Stock'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(upload_to='photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.PositiveIntegerField(verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_ordered',
            field=models.DateField(blank=True, null=True, verbose_name='Last Ordered'),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_quantity',
            field=models.PositiveIntegerField(default=5, verbose_name='Maximum Quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='primary_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.supplier', verbose_name='Primary Supplier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purcharse_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Reorder Level'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_minimum',
            field=models.PositiveIntegerField(default=10, verbose_name='Minimum Stock'),
        ),
        migrations.AlterField(
            model_name='item',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='possalesreport',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='possalesreport',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='possalesreport',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='possalesreport',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='possalesreport',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='possalesreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ourapp.purchaseorder', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(max_length=100, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='action',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Name'),
        ),
    ]
