# Generated by Django 5.2.1 on 2025-08-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0022_alter_cart_created_date_alter_cart_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='final_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Final Amount (with tax + shipping)'),
        ),
    ]
