# Generated by Django 5.2.1 on 2025-08-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0023_sale_final_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
