# Generated by Django 5.2.1 on 2025-08-19 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0024_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpos',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits (numbers only).', regex='^\\d{11}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits (numbers only).', regex='^\\d{11}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits (numbers only).', regex='^\\d{11}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits and contain only numbers.', regex='^\\d{11}$')]),
        ),
    ]
