# Generated by Django 5.2.1 on 2025-08-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0025_alter_customerpos_phone_alter_sale_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_promotion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Promotion Quantity')),
                ('discount_percent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Discount %')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=12, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='saleitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourapp.promotionitem'),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch No.')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('quantity_on_hand', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='On Hand')),
                ('reserved_promo', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Reserved for Promotion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ourapp.item', verbose_name='Item')),
            ],
            options={
                'ordering': ['exp_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleBatchConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='ourapp.saleitem')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.stockbatch')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ourapp.promotionitem')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_allocations', to='ourapp.stockbatch')),
            ],
        ),
    ]
